export type ReportFilterKey =
  | 'from'
  | 'to'
  | 'supplier'
  | 'category'
  | 'division'
  | 'country'
  | 'status'
  | 'paymentTerm'
  | 'modeOfShipment'
  | 'hsCode'
  | 'pol'
  | 'q'
  | 'shipVariance';

export type ReportColumn = { key: string; label: string; align?: 'left' | 'right' };

export type ReportDef = {
  id: string;
  group: string;
  title: string;
  description: string;
  filters: ReportFilterKey[];
  columns: ReportColumn[];
};

export const REPORT_CATALOG: ReportDef[] = [
  {
    id: 'purchase-orders',
    group: '1 · Purchase Order Format',
    title: 'Purchase Order Register',
    description: 'All POs with shipper, origin, terms, currency and grand total.',
    filters: ['from', 'to', 'supplier', 'status', 'q'],
    columns: [
      { key: 'poNumber', label: 'PO #' },
      { key: 'poDate', label: 'Date' },
      { key: 'status', label: 'Status' },
      { key: 'shipperName', label: 'Shipper' },
      { key: 'originOfGoods', label: 'Origin' },
      { key: 'shipVia', label: 'Ship Via' },
      { key: 'hsCode', label: 'HS Code' },
      { key: 'incoterms', label: 'Incoterms' },
      { key: 'currency', label: 'Currency' },
      { key: 'grandTotal', label: 'Grand Total', align: 'right' },
      { key: 'lineCount', label: 'Lines', align: 'right' },
    ],
  },
  {
    id: 'supplier-master',
    group: '2 · Supplier Master',
    title: 'Supplier Master Sheet',
    description: 'Master rows (PO + entry) with category, HS, lead time and certs.',
    filters: ['from', 'to', 'supplier', 'category', 'division', 'country', 'hsCode', 'pol', 'q'],
    columns: [
      { key: 'srNo', label: 'Sr.No', align: 'right' },
      { key: 'purchaseOrderNo', label: 'PO' },
      { key: 'entryDate', label: 'Date' },
      { key: 'shipperName', label: 'Shipper' },
      { key: 'productCategory', label: 'Category' },
      { key: 'division', label: 'Division' },
      { key: 'productItemCode', label: 'Item Code' },
      { key: 'productHsCode', label: 'HS Code' },
      { key: 'countryOfOrigin', label: 'COO' },
      { key: 'unitValue', label: 'Unit Value', align: 'right' },
      { key: 'totalQuantity', label: 'Qty', align: 'right' },
      { key: 'totalValue', label: 'Total Value', align: 'right' },
      { key: 'leadTimeDays', label: 'Lead Time', align: 'right' },
      { key: 'portOfLoading', label: 'POL' },
      { key: 'oekotexCert', label: 'Oekotex' },
      { key: 'isoCert', label: 'ISO' },
      { key: 'reachCert', label: 'Reach' },
      { key: 'poCompleted', label: 'PO Done' },
    ],
  },
  {
    id: 'import-open',
    group: '3 · Import Tracking',
    title: 'Current Status (Open)',
    description: 'Open import pipeline with lead-time and shipment fields.',
    filters: ['from', 'to', 'supplier', 'division', 'modeOfShipment', 'paymentTerm', 'pol', 'q'],
    columns: [
      { key: 'srNo', label: 'Sr.No', align: 'right' },
      { key: 'purchaseOrderNo', label: 'PO' },
      { key: 'division', label: 'Division' },
      { key: 'shipperName', label: 'Shipper' },
      { key: 'productDescription', label: 'Description' },
      { key: 'poQuantity', label: 'PO Qty', align: 'right' },
      { key: 'quantityShipped', label: 'Qty Shipped', align: 'right' },
      { key: 'unitValue', label: 'Unit Value', align: 'right' },
      { key: 'totalAmount', label: 'Amount', align: 'right' },
      { key: 'paymentTerm', label: 'Payment' },
      { key: 'modeOfShipment', label: 'Mode' },
      { key: 'incoterm', label: 'Incoterm' },
      { key: 'pol', label: 'POL' },
      { key: 'destinationPort', label: 'Destination' },
      { key: 'actualShipmentReadyDate', label: 'Actual Ready' },
      { key: 'remarks', label: 'Remarks' },
    ],
  },
  {
    id: 'import-closed',
    group: '4 · Closed Files',
    title: 'Current Closed Files',
    description: 'Closed shipments with QC, bank, insurance, logistics and clearance.',
    filters: ['from', 'to', 'supplier', 'category', 'division', 'paymentTerm', 'modeOfShipment', 'q'],
    columns: [
      { key: 'srNo', label: 'Sr.No', align: 'right' },
      { key: 'purchaseOrderNo', label: 'PO' },
      { key: 'category', label: 'Category' },
      { key: 'shipperName', label: 'Shipper' },
      { key: 'quantityShipped', label: 'Qty Shipped', align: 'right' },
      { key: 'totalAmount', label: 'Amount', align: 'right' },
      { key: 'paymentTerm', label: 'Payment' },
      { key: 'bankName', label: 'Bank' },
      { key: 'bankTtLcNumber', label: 'TT/LC No' },
      { key: 'bankRoe', label: 'R.O.E', align: 'right' },
      { key: 'qcRejectedQty', label: 'QC Rejected', align: 'right' },
      { key: 'qcMaterialFinancialLoss', label: 'QC Loss', align: 'right' },
      { key: 'insuranceCompany', label: 'Insurance' },
      { key: 'forwarder', label: 'Forwarder' },
      { key: 'gdNo', label: 'G.D No' },
      { key: 'shipmentClearanceDate', label: 'Clearance Date' },
      { key: 'clearanceAmount', label: 'Clearance Amt', align: 'right' },
      { key: 'delayCause', label: 'Delay Cause' },
    ],
  },
  {
    id: 'history-purchase',
    group: '5 · Histories',
    title: 'Purchase History',
    description: 'Derived purchase portfolio from Master + Import Tracking.',
    filters: ['from', 'to', 'supplier', 'category', 'q'],
    columns: [
      { key: 'srNo', label: 'Sr.No', align: 'right' },
      { key: 'category', label: 'Category' },
      { key: 'hsCode', label: 'HS Code' },
      { key: 'month', label: 'Month' },
      { key: 'productItemCode', label: 'Item Code' },
      { key: 'purchaseOrderNo', label: 'PO' },
      { key: 'poDate', label: 'PO Date' },
      { key: 'supplier', label: 'Supplier' },
      { key: 'description', label: 'Description' },
      { key: 'countryOfOrigin', label: 'COO' },
      { key: 'quantity', label: 'Qty', align: 'right' },
      { key: 'unitPrice', label: 'Unit Price', align: 'right' },
      { key: 'amount', label: 'Amount', align: 'right' },
      { key: 'paymentBankRef', label: 'Bank Ref' },
      { key: 'modeOfShipment', label: 'Mode' },
      { key: 'priceTerm', label: 'Price Term' },
      { key: 'roe', label: 'R.O.E', align: 'right' },
      { key: 'valueInPkr', label: 'Value PKR', align: 'right' },
    ],
  },
  {
    id: 'history-payment',
    group: '5 · Histories',
    title: 'Payment History',
    description: 'Payment-focused view with bank ref, ROE and PKR value.',
    filters: ['from', 'to', 'supplier', 'paymentTerm', 'q'],
    columns: [
      { key: 'srNo', label: 'Sr.No', align: 'right' },
      { key: 'purchaseOrderNo', label: 'PO' },
      { key: 'poDate', label: 'PO Date' },
      { key: 'supplier', label: 'Supplier' },
      { key: 'amount', label: 'Amount', align: 'right' },
      { key: 'paymentBankRef', label: 'Bank Ref' },
      { key: 'paymentTerm', label: 'Payment Term' },
      { key: 'roe', label: 'R.O.E', align: 'right' },
      { key: 'valueInPkr', label: 'Value PKR', align: 'right' },
      { key: 'modeOfShipment', label: 'Mode' },
      { key: 'priceTerm', label: 'Price Term' },
    ],
  },
  {
    id: 'history-operational',
    group: '5 · Histories',
    title: 'Operational History',
    description: 'Lead time, delivery vs actual ready, delay buckets and air lifts.',
    filters: ['from', 'to', 'supplier', 'modeOfShipment', 'q'],
    columns: [
      { key: 'srNo', label: 'Sr.No', align: 'right' },
      { key: 'purchaseOrderNo', label: 'PO' },
      { key: 'poDate', label: 'PO Date' },
      { key: 'supplier', label: 'Supplier' },
      { key: 'quantity', label: 'Qty', align: 'right' },
      { key: 'leadTimeDays', label: 'Lead Time', align: 'right' },
      { key: 'supplierDeliveryDate', label: 'Supplier Delivery' },
      { key: 'actualShipmentReadyDate', label: 'Actual Ready' },
      { key: 'ppSampleReadyDate', label: 'PP Sample' },
      { key: 'delay1to10', label: 'Delay 1–10', align: 'right' },
      { key: 'delay10to20', label: 'Delay 10–20', align: 'right' },
      { key: 'modeOfShipment', label: 'Mode' },
      { key: 'liftedByAirDueToDelay', label: 'Air due to delay' },
    ],
  },
  {
    id: 'analytics-suppliers-category',
    group: 'Analytics · SUPPLIERS catalog',
    title: 'Suppliers by Product Category',
    description: 'Counts and values for Fabrics / Accessories / Machinery / Chemicals.',
    filters: ['from', 'to', 'category', 'country'],
    columns: [
      { key: 'category', label: 'Category' },
      { key: 'supplierCount', label: 'Suppliers', align: 'right' },
      { key: 'poCount', label: 'POs', align: 'right' },
      { key: 'totalValue', label: 'Total Value', align: 'right' },
      { key: 'itemCodes', label: 'Distinct Item Codes', align: 'right' },
    ],
  },
  {
    id: 'analytics-orders-supplier',
    group: 'Analytics · SUPPLIERS catalog',
    title: 'Orders by Supplier / Country',
    description: 'Order totals grouped by supplier and country of origin.',
    filters: ['from', 'to', 'supplier', 'country', 'category'],
    columns: [
      { key: 'supplier', label: 'Supplier' },
      { key: 'country', label: 'Country' },
      { key: 'category', label: 'Category' },
      { key: 'poCount', label: 'POs', align: 'right' },
      { key: 'totalQty', label: 'Qty', align: 'right' },
      { key: 'avgUnitValue', label: 'Avg Unit Value', align: 'right' },
      { key: 'totalValue', label: 'Total Value', align: 'right' },
    ],
  },
  {
    id: 'analytics-certifications',
    group: 'Analytics · SUPPLIERS catalog',
    title: 'Certifications Report',
    description: 'Oekotex, ISO and Reach status by supplier and category.',
    filters: ['category', 'supplier', 'country'],
    columns: [
      { key: 'shipperName', label: 'Supplier' },
      { key: 'productCategory', label: 'Category' },
      { key: 'country', label: 'Country' },
      { key: 'oekotexCert', label: 'Oekotex' },
      { key: 'isoCert', label: 'ISO' },
      { key: 'reachCert', label: 'Reach' },
      { key: 'purchaseOrderNo', label: 'Latest PO' },
    ],
  },
  {
    id: 'analytics-supplier-status',
    group: 'Analytics · SUPPLIERS catalog',
    title: 'Supplier Status by Category',
    description: 'Manufacturer / Trader / Customer Source breakdown.',
    filters: ['category', 'country'],
    columns: [
      { key: 'productCategory', label: 'Category' },
      { key: 'supplierCategory', label: 'Supplier Status' },
      { key: 'count', label: 'Count', align: 'right' },
      { key: 'totalValue', label: 'Total Value', align: 'right' },
    ],
  },
  {
    id: 'analytics-hs-pol',
    group: 'Analytics · SUPPLIERS catalog',
    title: 'HS Codes & Port of Loading',
    description: 'HS list and shipments grouped by POL.',
    filters: ['hsCode', 'pol', 'category', 'from', 'to'],
    columns: [
      { key: 'productHsCode', label: 'HS Code' },
      { key: 'portOfLoading', label: 'POL' },
      { key: 'shipments', label: 'Shipments', align: 'right' },
      { key: 'totalQty', label: 'Qty', align: 'right' },
      { key: 'totalValue', label: 'Value', align: 'right' },
    ],
  },
  {
    id: 'analytics-po-variance',
    group: 'Analytics · SUPPLIERS catalog',
    title: 'PO Status & Ship Variance',
    description: 'PO issued / under process / completed plus short / over ship.',
    filters: ['from', 'to', 'supplier', 'shipVariance', 'status'],
    columns: [
      { key: 'purchaseOrderNo', label: 'PO' },
      { key: 'poDate', label: 'PO Date' },
      { key: 'shipperName', label: 'Supplier' },
      { key: 'masterDone', label: 'Master Done' },
      { key: 'itsStatus', label: 'ITS Status' },
      { key: 'poQuantity', label: 'PO Qty', align: 'right' },
      { key: 'quantityShipped', label: 'Shipped', align: 'right' },
      { key: 'variance', label: 'Variance', align: 'right' },
      { key: 'shipFlag', label: 'Flag' },
    ],
  },
  {
    id: 'analytics-division',
    group: 'Analytics · SUPPLIERS catalog',
    title: 'Division Summary',
    description: 'Division totals by month and value.',
    filters: ['from', 'to', 'division', 'category'],
    columns: [
      { key: 'division', label: 'Division' },
      { key: 'month', label: 'Month' },
      { key: 'poCount', label: 'POs', align: 'right' },
      { key: 'totalValue', label: 'Total Value', align: 'right' },
    ],
  },
  {
    id: 'analytics-payments',
    group: 'Analytics · SUPPLIERS catalog',
    title: 'Payment Mode Report',
    description: 'Payments by mode (LC / ADV / O/A / DA / DP) with bank and ROE.',
    filters: ['from', 'to', 'paymentTerm', 'supplier', 'category'],
    columns: [
      { key: 'purchaseOrderNo', label: 'PO' },
      { key: 'shipperName', label: 'Supplier' },
      { key: 'category', label: 'Category' },
      { key: 'paymentTerm', label: 'Payment Term' },
      { key: 'bankName', label: 'Bank' },
      { key: 'bankTtLcNumber', label: 'TT/LC' },
      { key: 'totalAmount', label: 'Amount', align: 'right' },
      { key: 'bankRoe', label: 'R.O.E', align: 'right' },
      { key: 'valuePkr', label: 'Value PKR', align: 'right' },
      { key: 'gdNo', label: 'G.D No' },
      { key: 'daysGdToBank', label: 'Days GD→Bank', align: 'right' },
    ],
  },
  {
    id: 'analytics-lead-time',
    group: 'Analytics · SUPPLIERS catalog',
    title: 'Lead Time & Delay Buckets',
    description: 'Lead-time maturity, PP samples and delay 1–10 / 10–20.',
    filters: ['from', 'to', 'supplier', 'division', 'modeOfShipment'],
    columns: [
      { key: 'purchaseOrderNo', label: 'PO' },
      { key: 'shipperName', label: 'Supplier' },
      { key: 'supplierDeliveryTime', label: 'Supplier LT', align: 'right' },
      { key: 'standardLeadTime', label: 'Std LT', align: 'right' },
      { key: 'ppSampleReadyDate', label: 'PP Sample' },
      { key: 'actualShipmentReadyDate', label: 'Actual Ready' },
      { key: 'delay1to10', label: 'Delay 1–10', align: 'right' },
      { key: 'delay10to20', label: 'Delay 10–20', align: 'right' },
      { key: 'modeOfShipment', label: 'Mode' },
    ],
  },
  {
    id: 'analytics-qc',
    group: 'Analytics · SUPPLIERS catalog',
    title: 'QC / Rejection Report',
    description: 'QC rejections, short shipment and material financial loss.',
    filters: ['from', 'to', 'supplier', 'category'],
    columns: [
      { key: 'purchaseOrderNo', label: 'PO' },
      { key: 'shipperName', label: 'Supplier' },
      { key: 'category', label: 'Category' },
      { key: 'qcOrderQty', label: 'Order Qty', align: 'right' },
      { key: 'qcRejectedQty', label: 'Rejected', align: 'right' },
      { key: 'qcLessQty', label: 'Less Qty', align: 'right' },
      { key: 'qcMaterialFinancialLoss', label: 'Financial Loss', align: 'right' },
      { key: 'qcReportReceivedDate', label: 'QC Report Date' },
      { key: 'qcClaimDate', label: 'Claim Date' },
    ],
  },
  {
    id: 'analytics-claims',
    group: 'Analytics · SUPPLIERS catalog',
    title: 'Claims Lifecycle',
    description: 'Claims inferred from QC claim date, rejection and financial loss (launched / accepted / received / rejected).',
    filters: ['from', 'to', 'supplier', 'category', 'status'],
    columns: [
      { key: 'purchaseOrderNo', label: 'PO' },
      { key: 'shipperName', label: 'Supplier' },
      { key: 'category', label: 'Category' },
      { key: 'claimStatus', label: 'Claim Status' },
      { key: 'qcClaimDate', label: 'Claim Date' },
      { key: 'qcRejectedQty', label: 'Rejected Qty', align: 'right' },
      { key: 'qcLessQty', label: 'Less Qty', align: 'right' },
      { key: 'claimExpenses', label: 'Claim Expenses / Loss', align: 'right' },
      { key: 'qcReportReceivedDate', label: 'QC Report Date' },
      { key: 'remarks', label: 'Remarks' },
    ],
  },
  {
    id: 'analytics-development-air-courier',
    group: 'Analytics · SUPPLIERS catalog',
    title: 'Development / Air & Courier Logistics',
    description: 'AIR and COURIER shipments with logistics amounts (development / urgent lift proxy).',
    filters: ['from', 'to', 'supplier', 'modeOfShipment', 'division'],
    columns: [
      { key: 'purchaseOrderNo', label: 'PO' },
      { key: 'shipperName', label: 'Supplier' },
      { key: 'division', label: 'Division' },
      { key: 'modeOfShipment', label: 'Mode' },
      { key: 'quantityShipped', label: 'Qty', align: 'right' },
      { key: 'totalAmount', label: 'Shipment Amount', align: 'right' },
      { key: 'forwarder', label: 'Forwarder' },
      { key: 'logisticsBillNo', label: 'Log. Bill No' },
      { key: 'logisticsWeightCbm', label: 'Weight/CBM' },
      { key: 'logisticsAmount', label: 'Logistics Amount', align: 'right' },
      { key: 'liftedByAirDueToDelay', label: 'Air due to delay' },
    ],
  },
  {
    id: 'analytics-dashboard-quarterly',
    group: 'Analytics · SUPPLIERS catalog',
    title: 'Supplier Dashboard (Quarterly)',
    description: 'Quarterly / half-yearly style rollup: open vs closed, value, QC loss and air lifts.',
    filters: ['from', 'to', 'supplier', 'category', 'division'],
    columns: [
      { key: 'period', label: 'Period' },
      { key: 'openCount', label: 'Open', align: 'right' },
      { key: 'closedCount', label: 'Closed', align: 'right' },
      { key: 'poCount', label: 'POs', align: 'right' },
      { key: 'totalValue', label: 'Total Value', align: 'right' },
      { key: 'qcLoss', label: 'QC Loss', align: 'right' },
      { key: 'airCourierCount', label: 'Air/Courier', align: 'right' },
      { key: 'logisticsSpend', label: 'Logistics Spend', align: 'right' },
    ],
  },
];

export function getReportDef(id: string) {
  return REPORT_CATALOG.find((r) => r.id === id) || null;
}
